-- LOCAL REHEARSAL ONLY: synthetic production-equivalent schema baseline.
-- Run only against a local Supabase PostgreSQL database; never use --linked.
-- This intentionally does not replay repository history or contain real data.
BEGIN;

CREATE TABLE public.companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT,
  currency TEXT NOT NULL DEFAULT 'RUB',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  timezone TEXT NOT NULL DEFAULT 'Europe/Moscow',
  language TEXT NOT NULL DEFAULT 'ru',
  is_default BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE public.marketplace_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  marketplace TEXT NOT NULL CHECK (marketplace IN ('wildberries', 'ozon', 'lamoda')),
  account_name TEXT NOT NULL,
  seller_id TEXT,
  api_key_encrypted TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_default BOOLEAN NOT NULL DEFAULT false,
  sync_enabled BOOLEAN NOT NULL DEFAULT false,
  last_sync_at TIMESTAMPTZ,
  last_successful_sync_at TIMESTAMPTZ,
  last_sync_status TEXT CHECK (last_sync_status IS NULL OR last_sync_status IN ('idle', 'running', 'success', 'partial', 'failed')),
  finance_lookback_days INTEGER NOT NULL DEFAULT 14,
  finance_gap_warn_days INTEGER NOT NULL DEFAULT 3,
  sync_heartbeat_at TIMESTAMPTZ,
  sync_lock_expires_at TIMESTAMPTZ,
  finance_latest_operation_date DATE,
  finance_latest_report_id BIGINT,
  finance_gap_days INTEGER,
  finance_recovery_needed BOOLEAN NOT NULL DEFAULT false,
  finance_last_sync_run_id UUID
);

CREATE TABLE public.brands (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE public.categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, parent_id BIGINT REFERENCES public.categories(id));
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id BIGINT REFERENCES public.brands(id), category_id BIGINT REFERENCES public.categories(id),
  created_at TIMESTAMPTZ DEFAULT now(), supplier_article TEXT NOT NULL, name TEXT NOT NULL,
  nm_id BIGINT NOT NULL, barcode TEXT, marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id)
);
CREATE UNIQUE INDEX idx_products_account_supplier_article ON public.products(marketplace_account_id, supplier_article);

CREATE TABLE public.product_variants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  nm_id BIGINT, tech_size TEXT NOT NULL DEFAULT '', barcode TEXT,
  created_at TIMESTAMPTZ DEFAULT now(), marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id),
  UNIQUE (product_id, tech_size, barcode)
);

CREATE TABLE public.wb_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date TIMESTAMPTZ, srid TEXT, nm_id BIGINT, quantity INTEGER DEFAULT 1,
  price NUMERIC(12,2), created_at TIMESTAMPTZ DEFAULT now(), product_id BIGINT REFERENCES public.products(id),
  sale_date DATE, status TEXT NOT NULL DEFAULT 'new', warehouse TEXT, tech_size TEXT, barcode TEXT,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id),
  price_with_disc NUMERIC(12,2) NOT NULL DEFAULT 0, last_change_date DATE
);
CREATE TABLE public.wb_sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_date TIMESTAMPTZ, srid TEXT, nm_id BIGINT, quantity INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT now(), product_id BIGINT REFERENCES public.products(id),
  revenue NUMERIC(12,2) NOT NULL DEFAULT 0, is_return BOOLEAN NOT NULL DEFAULT false,
  return_date DATE, tech_size TEXT, barcode TEXT,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id),
  price_with_disc NUMERIC(12,2) NOT NULL DEFAULT 0, for_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
  warehouse TEXT, sale_id TEXT NOT NULL, event_type TEXT NOT NULL,
  CHECK (event_type IN ('SALE', 'RETURN')),
  CHECK ((event_type = 'SALE' AND is_return = false) OR (event_type = 'RETURN' AND is_return = true))
);
CREATE UNIQUE INDEX idx_wb_sales_account_sale_id ON public.wb_sales(marketplace_account_id, sale_id);
CREATE INDEX idx_wb_sales_account_srid_lookup ON public.wb_sales(marketplace_account_id, srid);

CREATE TABLE public.wb_finance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id), nm_id BIGINT, operation_date DATE NOT NULL,
  operation_type TEXT NOT NULL CHECK (operation_type IN ('commission', 'logistics', 'return_logistics', 'storage', 'penalty', 'other')),
  amount NUMERIC(12,2) NOT NULL DEFAULT 0, description TEXT, source_key TEXT, srid TEXT,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id), realizationreport_id BIGINT,
  rrd_id BIGINT, rr_dt DATE, finance_category TEXT, wb_source_suffix TEXT, supplier_oper_name TEXT, finance_nature TEXT
);
CREATE UNIQUE INDEX idx_wb_finance_account_source_key ON public.wb_finance(marketplace_account_id, source_key) WHERE source_key IS NOT NULL;
CREATE UNIQUE INDEX idx_wb_finance_account_source_key_atomic ON public.wb_finance(marketplace_account_id, source_key);

CREATE TABLE public.wb_ads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date DATE, campaign_id BIGINT, campaign_name TEXT, supplier_article TEXT,
  spend NUMERIC(12,2), created_at TIMESTAMPTZ DEFAULT now(), product_id BIGINT REFERENCES public.products(id),
  nm_id BIGINT, campaign_date DATE, clicks INTEGER NOT NULL DEFAULT 0, impressions INTEGER NOT NULL DEFAULT 0,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id), source_key TEXT, updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.wb_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  tech_size TEXT NOT NULL DEFAULT '', barcode TEXT, warehouse TEXT, quantity INTEGER NOT NULL DEFAULT 0,
  last_synced_at TIMESTAMPTZ NOT NULL DEFAULT now(), marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id),
  quantity_full INTEGER NOT NULL DEFAULT 0, in_way_to_client INTEGER NOT NULL DEFAULT 0, in_way_from_client INTEGER NOT NULL DEFAULT 0,
  UNIQUE (product_id, tech_size, barcode, warehouse)
);
CREATE TABLE public.product_cost_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(), product_id BIGINT REFERENCES public.products(id),
  cost NUMERIC(12,2), effective_from DATE, effective_to DATE
);
CREATE TABLE public.historical_inventory_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, snapshot_date DATE NOT NULL,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id) ON DELETE CASCADE,
  warehouse_name TEXT NOT NULL DEFAULT '', brand TEXT NOT NULL DEFAULT '', subject TEXT NOT NULL DEFAULT '',
  seller_article TEXT NOT NULL DEFAULT '', nm_id BIGINT NOT NULL, barcode TEXT NOT NULL DEFAULT '', size TEXT NOT NULL DEFAULT '',
  quantity INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  in_way_to_client INTEGER NOT NULL DEFAULT 0, in_way_from_client INTEGER NOT NULL DEFAULT 0,
  UNIQUE (marketplace_account_id, snapshot_date, warehouse_name, nm_id, size, seller_article, barcode)
);
CREATE TABLE public.finance_incremental_sync_state (
  marketplace_account_id BIGINT PRIMARY KEY REFERENCES public.marketplace_accounts(id) ON DELETE CASCADE,
  mode TEXT NOT NULL DEFAULT 'idle' CHECK (mode IN ('idle', 'current_week', 'overlap_revalidation')),
  week_status TEXT NOT NULL DEFAULT 'idle' CHECK (week_status IN ('idle', 'in_progress', 'complete')),
  active_week_from DATE, active_week_to DATE, last_persisted_rrd_id BIGINT NOT NULL DEFAULT 0,
  overlap_revalidate_queue JSONB NOT NULL DEFAULT '[]', completed_weeks JSONB NOT NULL DEFAULT '{}',
  reports_last_request_at TIMESTAMPTZ, reports_next_request_not_before TIMESTAMPTZ,
  reports_server_retry_until TIMESTAMPTZ, reports_last_rate_limit_snapshot JSONB,
  lock_owner TEXT, lock_heartbeat_at TIMESTAMPTZ, lock_started_at TIMESTAMPTZ,
  latest_successful_data_date DATE, last_http_status INTEGER, last_wake_at TIMESTAMPTZ,
  last_error TEXT, last_cursor_before BIGINT, last_cursor_after BIGINT, last_rows_received INTEGER,
  last_rows_persisted INTEGER, last_has_more BOOLEAN, updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_finance_incremental_sync_state_next_request ON public.finance_incremental_sync_state(reports_next_request_not_before);

CREATE OR REPLACE FUNCTION public.orion_jwt_company_ids() RETURNS BIGINT[] LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(ARRAY(SELECT DISTINCT value::BIGINT FROM jsonb_array_elements_text(COALESCE(auth.jwt()->'app_metadata'->'orion'->'company_ids', '[]')) AS t(value) WHERE value ~ '^[0-9]+$'), ARRAY[]::BIGINT[]);
$$;
CREATE OR REPLACE FUNCTION public.orion_jwt_marketplace_account_ids_claim() RETURNS BIGINT[] LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(ARRAY(SELECT DISTINCT value::BIGINT FROM jsonb_array_elements_text(COALESCE(auth.jwt()->'app_metadata'->'orion'->'marketplace_account_ids', '[]')) AS t(value) WHERE value ~ '^[0-9]+$'), ARRAY[]::BIGINT[]);
$$;
CREATE OR REPLACE FUNCTION public.orion_allowed_marketplace_account_ids() RETURNS BIGINT[] LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH claimed AS (SELECT unnest(public.orion_jwt_marketplace_account_ids_claim()) AS id), by_company AS (
    SELECT ma.id FROM public.marketplace_accounts ma WHERE ma.company_id = ANY(public.orion_jwt_company_ids())
  ) SELECT COALESCE(ARRAY(SELECT DISTINCT id FROM by_company WHERE NOT EXISTS (SELECT 1 FROM claimed) OR id IN (SELECT id FROM claimed)), ARRAY[]::BIGINT[]);
$$;
REVOKE ALL ON FUNCTION public.orion_jwt_company_ids() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.orion_jwt_marketplace_account_ids_claim() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.orion_allowed_marketplace_account_ids() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.orion_jwt_company_ids(), public.orion_jwt_marketplace_account_ids_claim(), public.orion_allowed_marketplace_account_ids() TO authenticated, service_role;

-- Production-equivalent pre-fix RLS condition for the three affected tables.
ALTER TABLE public.wb_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wb_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_cost_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY service_role_all_wb_orders ON public.wb_orders FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_all_wb_sales ON public.wb_sales FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_role_all_product_cost_history ON public.product_cost_history FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY tenant_select_wb_orders ON public.wb_orders FOR SELECT TO authenticated USING (marketplace_account_id = ANY(public.orion_allowed_marketplace_account_ids()));
CREATE POLICY tenant_select_wb_sales ON public.wb_sales FOR SELECT TO authenticated USING (marketplace_account_id = ANY(public.orion_allowed_marketplace_account_ids()));
CREATE POLICY tenant_select_product_cost_history ON public.product_cost_history FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.products p WHERE p.id = product_cost_history.product_id AND p.marketplace_account_id = ANY(public.orion_allowed_marketplace_account_ids())));
CREATE POLICY dashboard_read_orders ON public.wb_orders FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY dashboard_read_sales ON public.wb_sales FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY dashboard_read_costs ON public.product_cost_history FOR SELECT TO anon, authenticated USING (true);
REVOKE ALL ON TABLE public.wb_orders, public.wb_sales, public.product_cost_history FROM anon;
GRANT SELECT ON TABLE public.wb_orders, public.wb_sales, public.product_cost_history TO authenticated, service_role;

INSERT INTO public.companies (id, name) VALUES (1, 'Synthetic Company A'), (2, 'Synthetic Company B');
INSERT INTO public.marketplace_accounts (id, company_id, marketplace, account_name, seller_id) VALUES
  (101, 1, 'wildberries', 'Synthetic A1', 'synthetic-a1'), (102, 1, 'wildberries', 'Synthetic A2', 'synthetic-a2'), (201, 2, 'wildberries', 'Synthetic B1', 'synthetic-b1');
INSERT INTO public.brands (id, name) VALUES (1, 'Synthetic Brand');
INSERT INTO public.categories (id, name) VALUES (1, 'Synthetic Category');
INSERT INTO public.products (id, brand_id, category_id, supplier_article, name, nm_id, marketplace_account_id) VALUES
  (1001, 1, 1, 'A1-SKU', 'Synthetic A1 Product', 10001, 101),
  (1002, 1, 1, 'A2-SKU', 'Synthetic A2 Product', 10002, 102),
  (2001, 1, 1, 'B1-SKU', 'Synthetic B1 Product', 20001, 201);
INSERT INTO public.product_variants (id, product_id, nm_id, tech_size, barcode, marketplace_account_id) VALUES
  (5001, 1001, 10001, 'S', 'A-S', 101), (5002, 1001, 10001, 'M', NULL, 101), (6001, 2001, 20001, 'S', 'B-S', 201);
INSERT INTO public.wb_orders (id, order_date, srid, nm_id, product_id, marketplace_account_id, price_with_disc) VALUES
  (1, now(), 'A-ORDER', 10001, 1001, 101, 100), (2, now(), 'B-ORDER', 20001, 2001, 201, 200);
INSERT INTO public.wb_sales (id, sale_date, srid, nm_id, product_id, marketplace_account_id, revenue, price_with_disc, for_pay, sale_id, event_type, is_return) VALUES
  (1, now(), 'A-SALE', 10001, 1001, 101, 100, 100, 80, 'A-SALE-1', 'SALE', false),
  (2, now(), 'B-SALE', 20001, 2001, 201, 200, 200, 160, 'B-SALE-1', 'SALE', false);
INSERT INTO public.wb_finance (id, product_id, nm_id, operation_date, operation_type, amount, source_key, marketplace_account_id) VALUES
  (1, 1001, 10001, CURRENT_DATE, 'commission', -10, 'synthetic:a1', 101),
  (2, 2001, 20001, CURRENT_DATE, 'commission', -20, 'synthetic:b1', 201);
SELECT setval(pg_get_serial_sequence('public.wb_finance', 'id'), (SELECT max(id) FROM public.wb_finance), true);
INSERT INTO public.product_cost_history (id, product_id, cost, effective_from) VALUES
  (1, 1001, 25, CURRENT_DATE), (2, 2001, 50, CURRENT_DATE);
INSERT INTO public.historical_inventory_snapshots (snapshot_date, marketplace_account_id, warehouse_name, seller_article, nm_id, barcode, size, quantity) VALUES
  (CURRENT_DATE, 101, 'Legacy Warehouse', 'A1-SKU', 10001, 'A-S', 'S', 7);
INSERT INTO public.finance_incremental_sync_state (marketplace_account_id) VALUES (101), (102), (201);
SELECT setval(pg_get_serial_sequence('public.companies', 'id'), 2, true);
SELECT setval(pg_get_serial_sequence('public.marketplace_accounts', 'id'), 201, true);
SELECT setval(pg_get_serial_sequence('public.products', 'id'), 2001, true);
COMMIT;
