/**
 * Seed Financial Engine V4 Knowledge Objects — Sprint 12.5.
 * Formulas sourced from src/lib/financial-engine.ts, profit-engine-model-b.ts,
 * profit-engine-model-c.ts, docs/01-business/GLOSSARY.md, docs/01-business/ACCOUNTING_RULES.md,
 * docs/99-legacy/estimated-tax-models.md, .cursor/rules/estimated-tax-dual-model.mdc
 */

import type { OrionKnowledgeObject } from "@/lib/orion/types";

const TS = "2026-08-12T00:00:00.000Z";

function fe(partial: Partial<OrionKnowledgeObject> & Pick<OrionKnowledgeObject, "id" | "title" | "description" | "module" | "category" | "authority_level" | "confidence" | "source_priority" | "keywords" | "tags" | "synonyms" | "abbreviations" | "sources" | "relationships">): OrionKnowledgeObject {
  return {
    aliases: [],
    owner: "Financial Engine",
    business_owner: "Financial Engine",
    technical_owner: "Platform Architecture",
    verification_status: "verified",
    locale: "en",
    lifecycle: "verified",
    version: "1.0.0",
    created_at: TS,
    updated_at: TS,
    tenant_scope: "global",
    ...partial,
  };
}

export const FINANCIAL_ENGINE_KNOWLEDGE_OBJECTS: OrionKnowledgeObject[] = [
  fe({
    id: "FE-018",
    title: "Financial Engine V4",
    aliases: ["Commercial Performance V4", "Profit Engine V4"],
    description:
      "The project's settled commercial calculation system that produces Commercial Performance results from warehouse facts and published business rules.",
    module: "Financial Engine",
    category: "architecture",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["financial engine", "v4", "commercial performance", "profit engine"],
    tags: ["financial-engine", "v4", "architecture"],
    synonyms: ["Commercial Performance Engine"],
    abbreviations: ["FE"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#financial-engine", priority: 1 },
      { kind: "documentation", ref: "docs/01-business/ACCOUNTING_RULES.md", priority: 2 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "implements", target_id: "FE-016" },
      { type: "used_by", target_id: "DASH-001" },
      { type: "defined_by", target_id: "BIZ-001" },
    ],
    formula:
      "Sales = Σ priceWithDisc; Marketplace Fee = Sales − forPay; Revenue = Σ ppvz_for_pay; Estimated Tax = Tax% × Σ finishedPrice; Net Profit = Revenue − costs − Estimated Tax",
    data_sources: ["wb_sales", "wb_finance"],
  }),
  fe({
    id: "FE-016",
    title: "Model B (Commercial Performance)",
    aliases: ["Commercial Performance", "Commercial Profit", "Model B", "What is Model B", "What is Model B?"],
    description:
      "The primary commercial profitability model for historical reporting: money-flow from sales through expenses to Net Profit on the Dashboard and related reports.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["model b", "commercial performance", "historical profit"],
    tags: ["model-b", "commercial-performance"],
    synonyms: ["Commercial Performance Model"],
    abbreviations: ["MB"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#commercial-performance", priority: 1 },
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#31-commercial-performance-financial-engine", priority: 1 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-b.ts", priority: 5 },
    ],
    relationships: [
      { type: "implemented_by", target_id: "FE-018" },
      { type: "related_to", target_id: "FE-017" },
      { type: "defined_by", target_id: "BIZ-001" },
    ],
  }),
  fe({
    id: "FE-017",
    title: "Model C (Settlement Profit)",
    aliases: ["Settlement Profit", "Model C", "What is Model C", "What is Model C?"],
    description:
      "Settlement-oriented profit framing (historically Model C). Revenue = netForPay; Net Profit deducts logistics, storage, penalties, deductions, acceptance, product cost, and advertising. Marketplace fees are informational only.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["model c", "settlement profit", "netForPay"],
    tags: ["model-c", "settlement"],
    synonyms: ["Settlement Profit Model"],
    abbreviations: ["MC"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#settlement-profit", priority: 1 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-c.ts", priority: 5 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-016" },
      { type: "related_to", target_id: "FE-014" },
    ],
    formula:
      "Revenue = netForPay; Net Profit = netForPay − Logistics − Storage − Penalties − Deductions − Acceptance − Product Cost − Advertising",
    exceptions: ["Marketplace Fees are informational only and must not be deducted in Model C."],
  }),
  fe({
    id: "FE-001",
    title: "Gross Sales",
    aliases: ["How is Gross Sales calculated", "How is Gross Sales calculated?"],
    description:
      "Gross merchandise sales for completed sales in the period, before subtracting returned sales in the Commercial Performance display story.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["gross sales", "sales volume"],
    tags: ["sales", "commercial-performance"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#gross-sales", priority: 1 },
      { kind: "implementation", ref: "src/lib/sales-revenue-resolution.ts", priority: 5 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-002" },
      { type: "related_to", target_id: "FE-015" },
    ],
    formula: "Gross Sales = Σ priceWithDisc (completed sales, pre-return display)",
  }),
  fe({
    id: "FE-002",
    title: "Net Sales",
    aliases: ["Sales", "What is Sales", "What is Sales?"],
    description:
      "Display sales after returns: Gross Sales minus Returned Sales. Used for seller-facing sales presentation; not a synonym for Revenue.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["net sales", "sales", "priceWithDisc"],
    tags: ["sales", "net-sales"],
    synonyms: ["Sales (Commercial Performance)"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#net-sales", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-b.ts", priority: 5 },
    ],
    relationships: [
      { type: "depends_on", target_id: "FE-001" },
      { type: "depends_on", target_id: "FE-015" },
      { type: "related_to", target_id: "FE-004" },
    ],
    formula: "Net Sales = Gross Sales − Returned Sales; Sales = Σ priceWithDisc",
    data_sources: ["wb_sales.priceWithDisc"],
  }),
  fe({
    id: "FE-003",
    title: "Revenue",
    aliases: ["Seller Revenue", "What is Revenue", "What is Revenue?"],
    description:
      "In Commercial Performance, the seller's marketplace payable amount for the period — the commercial top line from which operating costs and Estimated Tax are reasoned toward profit.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["revenue", "ppvz_for_pay", "seller payable"],
    tags: ["revenue", "commercial-performance"],
    synonyms: ["Seller Payable"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#revenue", priority: 1 },
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#41-what-revenue-means", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "depends_on", target_id: "FE-002" },
      { type: "related_to", target_id: "FE-014" },
      { type: "defined_by", target_id: "BIZ-001" },
    ],
    formula: "Revenue = Σ ppvz_for_pay (Finance API)",
    data_sources: ["wb_finance.ppvz_for_pay"],
  }),
  fe({
    id: "FE-004",
    title: "Marketplace Fee",
    aliases: ["Commission", "Marketplace Fees", "What is Marketplace Fee", "How is Marketplace Fee calculated"],
    description:
      "The marketplace fee take in the commercial fee story. Shown for understanding; not deducted again in Net Profit when already reflected before Revenue.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["marketplace fee", "commission", "forPay"],
    tags: ["fees", "commercial-performance"],
    synonyms: ["Commission"],
    abbreviations: ["MF"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#marketplace-fee", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [{ type: "depends_on", target_id: "FE-002" }],
    formula: "Marketplace Fee = max(0, Sales − Sales API forPay)",
    exceptions: ["Never derived from ppvz_* fields."],
  }),
  fe({
    id: "FE-005",
    title: "Product Cost",
    aliases: ["COGS", "How is Product Cost calculated"],
    description: "Cost of goods attributed to sold units for the period, based on maintained unit costs.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["product cost", "cogs", "unit cost"],
    tags: ["costs"],
    synonyms: ["COGS"],
    abbreviations: ["PC"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#product-cost", priority: 1 },
      { kind: "implementation", ref: "src/services/cost-service.ts", priority: 5 },
    ],
    relationships: [{ type: "used_by", target_id: "FE-013" }],
  }),
  fe({
    id: "FE-006",
    title: "Logistics",
    aliases: [],
    description: "Marketplace logistics costs attributed to the selected period in Commercial Performance.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["logistics", "delivery"],
    tags: ["costs", "logistics"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#logistics", priority: 1 },
      { kind: "implementation", ref: "src/lib/wb-settlement.ts", priority: 5 },
    ],
    relationships: [{ type: "used_by", target_id: "FE-013" }],
    data_sources: ["wb_finance"],
  }),
  fe({
    id: "FE-007",
    title: "Storage",
    aliases: [],
    description: "Marketplace storage costs for the period.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["storage"],
    tags: ["costs", "storage"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#54-storage", priority: 1 },
    ],
    relationships: [{ type: "used_by", target_id: "FE-013" }],
  }),
  fe({
    id: "FE-008",
    title: "Acceptance",
    aliases: [],
    description: "Marketplace acceptance (intake) operation costs for the period.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["acceptance"],
    tags: ["costs"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#55-acceptance", priority: 1 },
    ],
    relationships: [{ type: "used_by", target_id: "FE-013" }],
  }),
  fe({
    id: "FE-009",
    title: "Penalties",
    aliases: [],
    description: "Marketplace penalty amounts for the period.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["penalties"],
    tags: ["costs"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#penalties", priority: 1 },
    ],
    relationships: [{ type: "used_by", target_id: "FE-013" }],
  }),
  fe({
    id: "FE-010",
    title: "Adjustments",
    aliases: ["Other Costs", "Other Marketplace Costs", "Other / Adjustments"],
    description:
      "Marketplace financial adjustments for the period, including advertising and other holds not classified as Fee, Logistics, Storage, Acceptance, or Penalties.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["adjustments", "other costs", "deductions"],
    tags: ["costs", "adjustments"],
    synonyms: ["Other Costs"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#adjustments", priority: 1 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-011" },
      { type: "used_by", target_id: "FE-013" },
    ],
  }),
  fe({
    id: "FE-011",
    title: "Advertising",
    aliases: [],
    description:
      "Advertising/marketing spend. In Commercial Performance commonly included inside Adjustments when sourced from finance adjustments.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["advertising", "ads", "marketing"],
    tags: ["costs", "advertising"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#advertising", priority: 1 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-010" },
      { type: "used_by", target_id: "FE-013" },
    ],
  }),
  fe({
    id: "FE-012",
    title: "Estimated Tax",
    aliases: ["Tax", "Tax estimate"],
    description:
      "Historical reporting tax estimate on completed sales. In Commercial Performance: Tax Rate × Σ finishedPrice (Customer Paid). Smart Pricing uses a different base intentionally.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["estimated tax", "tax", "finishedPrice"],
    tags: ["tax", "commercial-performance"],
    synonyms: ["Tax estimate"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#estimated-tax", priority: 1 },
      { kind: "documentation", ref: "docs/99-legacy/estimated-tax-models.md", priority: 3 },
      { kind: "documentation", ref: ".cursor/rules/estimated-tax-dual-model.mdc", priority: 3 },
      { kind: "implementation", ref: "src/lib/financial-engine-tax.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-013" },
      { type: "defined_by", target_id: "ARCH-001" },
    ],
    formula: "Estimated Tax = Tax Rate × Σ finishedPrice (historical reporting / Financial Engine)",
    exceptions: [
      "Smart Pricing uses Tax Rate × (Sale Price − Marketplace Fee) — do not unify with reporting.",
    ],
  }),
  fe({
    id: "FE-013",
    title: "Net Profit",
    aliases: ["Final Net Profit", "How is Net Profit calculated"],
    description:
      "Commercial profit after Estimated Tax in Commercial Performance — the primary after-tax profitability KPI for historical reporting.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["net profit", "profit", "operating profit"],
    tags: ["profit", "commercial-performance"],
    synonyms: ["Final Net Profit"],
    abbreviations: ["NP"],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#net-profit", priority: 1 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-b.ts", priority: 5 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "depends_on", target_id: "FE-003" },
      { type: "depends_on", target_id: "FE-005" },
      { type: "depends_on", target_id: "FE-006" },
      { type: "depends_on", target_id: "FE-012" },
      { type: "defined_by", target_id: "FE-016" },
    ],
    formula:
      "Net Profit = Revenue − Product Cost − Logistics − Storage − Acceptance − Penalties − Other/Adjustments − Advertising − Estimated Tax",
  }),
  fe({
    id: "FE-014",
    title: "WB Settlement",
    aliases: ["Settlement", "Settlement view", "What is WB Settlement", "What is WB Settlement?"],
    description:
      "Settlement-oriented view of marketplace payout figures for reconciliation. Distinct from Commercial Performance; not a replacement commercial P&L.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["wb settlement", "settlement", "payout", "realization", "what is wb settlement"],
    tags: ["settlement"],
    synonyms: ["Settlement"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#wb-settlement", priority: 1 },
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#32-wb-settlement-settlement-framing", priority: 1 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-003" },
      { type: "related_to", target_id: "FE-017" },
    ],
    exceptions: ["Revenue (Commercial Performance) ≠ Settlement Amount / Seller Payout."],
  }),
  fe({
    id: "FE-015",
    title: "Return Handling",
    aliases: ["Returns", "Returned Sales", "How are returns handled"],
    description:
      "Returns affect the sales story (Gross Sales, Returned Sales, Net Sales) and related quantities. They do not redefine Revenue into Customer Paid or Net Sales.",
    module: "Financial Engine",
    category: "process",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["returns", "returned sales", "refunds"],
    tags: ["returns", "sales"],
    synonyms: ["Returned Sales"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#42-conceptual-boundaries", priority: 1 },
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#returned-sales", priority: 1 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-001" },
      { type: "related_to", target_id: "FE-002" },
    ],
  }),
  fe({
    id: "FE-019",
    title: "priceWithDisc",
    aliases: ["price_with_disc", "Seller-discounted price"],
    description:
      "Wildberries Sales API seller-discounted unit price. Basis for Sales = Σ priceWithDisc on completed sales. Stored as wb_sales.price_with_disc. Not finishedPrice or forPay.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["priceWithDisc", "price_with_disc", "what is priceWithDisc"],
    tags: ["sales", "fields"],
    synonyms: ["Seller discounted price"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#net-sales", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-002" },
      { type: "related_to", target_id: "FE-020" },
      { type: "related_to", target_id: "FE-021" },
    ],
    formula: "Sales = Σ priceWithDisc × quantity",
    data_sources: ["wb_sales.price_with_disc"],
  }),
  fe({
    id: "FE-020",
    title: "finishedPrice",
    aliases: ["Customer Paid", "finished price"],
    description:
      "Sales API customer-paid amount (finishedPrice). Persisted as wb_sales.revenue. Basis for historical Estimated Tax = Tax% × Σ finishedPrice. Not Commercial Performance Revenue.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["finishedPrice", "what is finishedPrice", "customer paid"],
    tags: ["sales", "fields", "tax"],
    synonyms: ["Customer Paid"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#customer-paid", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-012" },
      { type: "related_to", target_id: "FE-003" },
    ],
    formula: "Estimated Tax = Tax Rate × Σ finishedPrice",
    data_sources: ["wb_sales.revenue"],
  }),
  fe({
    id: "FE-021",
    title: "forPay",
    aliases: ["Sales API forPay", "for_pay"],
    description:
      "Sales API seller-payable per sale (forPay). With Sales derives Marketplace Fee = max(0, Sales − Σ forPay). Stored as wb_sales.for_pay. Differs from Finance ppvz_for_pay.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["forPay", "for_pay", "what is forPay"],
    tags: ["sales", "fields"],
    synonyms: ["Sales API forPay"],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#marketplace-fee", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-004" },
      { type: "related_to", target_id: "FE-022" },
      { type: "related_to", target_id: "FE-035" },
    ],
    data_sources: ["wb_sales.for_pay"],
  }),
  fe({
    id: "FE-022",
    title: "ppvz_for_pay",
    aliases: ["Finance ppvz_for_pay", "What is ppvz_for_pay"],
    description:
      "Finance API payable field per transaction. Commercial Performance Revenue = Σ ppvz_for_pay. Stored in wb_finance. Can differ from Sales API forPay.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["ppvz_for_pay", "what is ppvz_for_pay"],
    tags: ["finance", "revenue"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#revenue", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-003" },
      { type: "related_to", target_id: "FE-035" },
    ],
    formula: "Revenue = Σ ppvz_for_pay",
    data_sources: ["wb_finance.ppvz_for_pay"],
  }),
  fe({
    id: "FE-023",
    title: "netForPay",
    aliases: ["Net for pay"],
    description: "Settlement-oriented net payable used in Model C where Revenue = netForPay. Distinct from Commercial Performance Revenue.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["netForPay", "net for pay"],
    tags: ["settlement"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#settlement-profit", priority: 1 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-c.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-017" },
      { type: "related_to", target_id: "FE-014" },
    ],
  }),
  fe({
    id: "FE-024",
    title: "Acquiring Fee",
    aliases: ["Acquiring"],
    description: "Payment acquiring costs (Finance ACQUIRING). Component of marketplace cost presentation.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["acquiring", "acquiring fee"],
    tags: ["fees"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#acquiring", priority: 1 },
      { kind: "implementation", ref: "src/types/finance.ts", priority: 5 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-004" },
      { type: "related_to", target_id: "FE-036" },
    ],
  }),
  fe({
    id: "FE-025",
    title: "PPVZ VW",
    aliases: ["PPVZ_VW", "ppvz_vw"],
    description: "Finance PPVZ_VW fee component in marketplace cost presentation.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["ppvz vw", "PPVZ_VW"],
    tags: ["fees"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#marketplace-fee", priority: 1 },
      { kind: "implementation", ref: "src/types/finance.ts", priority: 5 },
      { kind: "implementation", ref: "src/lib/finance-rollup.ts", priority: 5 },
    ],
    relationships: [{ type: "related_to", target_id: "FE-036" }],
  }),
  fe({
    id: "FE-026",
    title: "PPVZ Reward",
    aliases: ["PPVZ_REWARD", "ppvz_reward"],
    description: "Finance PPVZ_REWARD component in marketplace cost presentation.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["ppvz reward", "PPVZ_REWARD"],
    tags: ["fees"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#marketplace-fee", priority: 1 },
      { kind: "implementation", ref: "src/types/finance.ts", priority: 5 },
      { kind: "implementation", ref: "src/lib/finance-rollup.ts", priority: 5 },
    ],
    relationships: [{ type: "related_to", target_id: "FE-036" }],
  }),
  fe({
    id: "FE-027",
    title: "Sales vs Revenue Distinction",
    aliases: [
      "Difference between Sales and Revenue",
      "What is the difference between Sales and Revenue",
      "What is the difference between Sales and Revenue?",
    ],
    description:
      "Sales (Σ priceWithDisc) is merchandise presentation. Revenue (Σ ppvz_for_pay) is seller payable. Not interchangeable.",
    module: "Financial Engine",
    category: "comparison",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["difference between sales and revenue", "sales vs revenue", "what is sales", "difference between revenue and settlement", "revenue vs settlement"],
    tags: ["comparison"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#42-conceptual-boundaries", priority: 1 },
    ],
    relationships: [
      { type: "references", target_id: "FE-002" },
      { type: "references", target_id: "FE-003" },
    ],
  }),
  fe({
    id: "FE-028",
    title: "Units Sold",
    aliases: ["Completed units", "What are Units Sold", "What are Units Sold?"],
    description: "Completed non-return sale units in period from wb_sales (is_return = false).",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["units sold", "what are units sold", "completed units"],
    tags: ["kpi"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#units-sold", priority: 1 },
      { kind: "implementation", ref: "src/lib/financial-engine.ts", priority: 5 },
    ],
    relationships: [{ type: "related_to", target_id: "FE-029" }],
    data_sources: ["wb_sales"],
  }),
  fe({
    id: "FE-029",
    title: "Returned Units and Net Units",
    aliases: ["Returned Units", "Net Units"],
    description: "Returned Units from is_return sales. Net Units = Units Sold minus returns. Distinct from Returned Sales value.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["returned units", "net units", "how are returns handled"],
    tags: ["returns", "kpi"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#returned-units", priority: 1 },
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#42-conceptual-boundaries", priority: 1 },
    ],
    relationships: [
      { type: "depends_on", target_id: "FE-015" },
      { type: "related_to", target_id: "FE-028" },
    ],
  }),
  fe({
    id: "FE-030",
    title: "Orders KPI",
    aliases: ["Orders", "Cancelled Orders", "Active Orders"],
    description: "Order events from wb_orders by order_date. Distinct from Units Sold (completed buyouts).",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["orders", "cancelled orders", "active orders"],
    tags: ["kpi", "orders"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#orders", priority: 1 },
      { kind: "implementation", ref: "src/services/persisted-query-service.ts", priority: 5 },
    ],
    relationships: [{ type: "related_to", target_id: "FE-028" }],
    data_sources: ["wb_orders"],
  }),
  fe({
    id: "FE-031",
    title: "Buyout",
    aliases: ["Buyout rate", "Conversion"],
    description: "Demand-to-sale conversion between orders and completed sales. Chart 'Purchases' label = Buyout, not Purchases module.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["buyout", "conversion"],
    tags: ["kpi"],
    synonyms: [],
    abbreviations: [],
    sources: [{ kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#buyout", priority: 1 }],
    relationships: [
      { type: "related_to", target_id: "FE-030" },
      { type: "related_to", target_id: "FE-028" },
    ],
  }),
  fe({
    id: "FE-032",
    title: "Profit Margin",
    aliases: ["Margin"],
    description: "Ratio from Commercial Performance (Net Profit vs Revenue/Sales per surface). Presentation only.",
    module: "Financial Engine",
    category: "calculation",
    authority_level: "financial_engine",
    confidence: "Verified",
    source_priority: "financial_engine",
    keywords: ["profit margin", "margin"],
    tags: ["profit"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#operating-profit", priority: 1 },
      { kind: "implementation", ref: "src/lib/profit-engine-model-b.ts", priority: 5 },
    ],
    relationships: [
      { type: "depends_on", target_id: "FE-013" },
      { type: "depends_on", target_id: "FE-003" },
    ],
  }),
  fe({
    id: "FE-033",
    title: "Return Logistics",
    aliases: ["Rebill logistics"],
    description: "RETURN_LOGISTICS finance category — return shipment costs. Distinct from Returned Sales and forward Logistics.",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["return logistics"],
    tags: ["costs", "returns"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#return-logistics", priority: 1 },
      { kind: "implementation", ref: "src/lib/finance-category.ts", priority: 5 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-006" },
      { type: "related_to", target_id: "FE-015" },
    ],
  }),
  fe({
    id: "FE-034",
    title: "Sale Date vs Finance Settlement Date",
    aliases: ["Reporting date axes", "sale_date vs operation_date"],
    description:
      "Sales metrics: sale_date. Finance/Revenue/costs: operation_date. Orders: order_date. Settlement: finance/settlement time. Do not merge date axes.",
    module: "Financial Engine",
    category: "policy",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: [
      "which date determines finance settlement reporting",
      "sale date",
      "settlement date",
      "operation_date",
    ],
    tags: ["dates"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md", priority: 1 },
      { kind: "implementation", ref: "src/services/persisted-query-service.ts", priority: 5 },
    ],
    relationships: [
      { type: "used_by", target_id: "FE-003" },
      { type: "used_by", target_id: "FE-014" },
    ],
  }),
  fe({
    id: "FE-035",
    title: "Sales API vs Finance API Reconciliation",
    aliases: ["forPay vs ppvz_for_pay", "Why Sales API differs from Finance"],
    description:
      "Sales forPay and Finance ppvz_for_pay differ by feed/timing/settlement. Revenue uses Finance. Marketplace Fee uses Sales − forPay. State API and date axis when reconciling.",
    module: "Financial Engine",
    category: "comparison",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["why can sales api forpay differ", "sales api vs finance", "reconciliation"],
    tags: ["reconciliation"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md#42-conceptual-boundaries", priority: 1 },
      { kind: "implementation", ref: "src/lib/wb-settlement.ts", priority: 5 },
    ],
    relationships: [
      { type: "references", target_id: "FE-021" },
      { type: "references", target_id: "FE-022" },
    ],
  }),
  fe({
    id: "FE-036",
    title: "Effective Marketplace Cost Presentation",
    aliases: ["Per-sale marketplace costs"],
    description:
      "Finance presentation: COMMISSION + ACQUIRING + PPVZ_REWARD + PPVZ_VW + OTHER from wb_finance. Separate from Marketplace Fee formula (Sales − forPay).",
    module: "Financial Engine",
    category: "definition",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["effective marketplace cost", "marketplace fees breakdown"],
    tags: ["fees"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "implementation", ref: "src/types/finance.ts", priority: 5 },
      { kind: "business_rule", ref: "docs/01-business/GLOSSARY.md#marketplace-fee", priority: 1 },
    ],
    relationships: [
      { type: "related_to", target_id: "FE-004" },
      { type: "related_to", target_id: "FE-024" },
    ],
    formula: "COMMISSION + ACQUIRING + PPVZ_REWARD + PPVZ_VW + OTHER",
  }),
  fe({
    id: "BIZ-001",
    title: "Accounting Rules Framework",
    aliases: ["Accounting Rules"],
    description:
      "Canonical accounting framework for money-related calculations and reports. Defines financial models, revenue recognition boundaries, and cost categories.",
    module: "Business Rules",
    category: "policy",
    authority_level: "business_rule",
    confidence: "Verified",
    source_priority: "business_rule",
    keywords: ["accounting", "business rules", "financial models"],
    tags: ["business-rules", "accounting"],
    synonyms: [],
    abbreviations: [],
    sources: [{ kind: "business_rule", ref: "docs/01-business/ACCOUNTING_RULES.md", priority: 1 }],
    relationships: [{ type: "related_to", target_id: "FE-016" }],
    owner: "Product Owner",
    business_owner: "Product Owner",
    technical_owner: "Platform Architecture",
  }),
  fe({
    id: "ARCH-001",
    title: "Estimated Tax Dual Model",
    aliases: ["Dual Tax Models"],
    description:
      "The project intentionally maintains two Estimated Tax bases: historical reporting uses Σ finishedPrice; Smart Pricing uses Sale − Marketplace Fee. Do not unify.",
    module: "Architecture",
    category: "policy",
    authority_level: "architecture_decision",
    confidence: "Verified",
    source_priority: "architecture_decision",
    keywords: ["estimated tax", "dual model", "smart pricing tax"],
    tags: ["architecture", "tax"],
    synonyms: [],
    abbreviations: [],
    sources: [
      { kind: "documentation", ref: ".cursor/rules/estimated-tax-dual-model.mdc", priority: 2 },
      { kind: "documentation", ref: "docs/99-legacy/estimated-tax-models.md", priority: 3 },
    ],
    relationships: [{ type: "related_to", target_id: "FE-012", note: "Defines tax dual-model policy for FE-012" }],
    owner: "Platform Architecture",
    business_owner: "Financial Engine",
    technical_owner: "Platform Architecture",
    exceptions: [
      "Reporting: Tax Rate × Σ finishedPrice",
      "Smart Pricing: Tax Rate × (Sale − Marketplace Fee)",
    ],
  }),
];
