-- Sprint 2: company tax configuration and manually entered operating expenses.
-- No tax amounts, WB facts, Purchases, or V4 rows are rewritten.
BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE public.company_tax_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  tax_system TEXT NOT NULL DEFAULT 'USN' CHECK (tax_system = 'USN'),
  tax_object TEXT NOT NULL CHECK (tax_object IN ('USN_INCOME', 'USN_INCOME_MINUS_EXPENSES')),
  tax_rate NUMERIC(5,2) NOT NULL CHECK (tax_rate > 0 AND tax_rate <= 100),
  minimum_tax_rate NUMERIC(5,2) NOT NULL DEFAULT 1 CHECK (minimum_tax_rate = 1),
  effective_from DATE NOT NULL,
  effective_to DATE,
  region_code TEXT,
  vat_status TEXT NOT NULL DEFAULT 'UNKNOWN' CHECK (vat_status IN ('UNKNOWN', 'EXEMPT', 'VAT_APPLICABLE')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT company_tax_profiles_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
  CONSTRAINT company_tax_profiles_no_overlap EXCLUDE USING gist (
    company_id WITH =,
    daterange(effective_from, effective_to, '[]') WITH &&
  )
);
CREATE INDEX company_tax_profiles_company_dates ON public.company_tax_profiles(company_id, effective_from DESC);

-- Append a new election atomically; never modify a past effective interval.
CREATE FUNCTION public.orion_append_company_tax_profile(
  p_company_id BIGINT, p_tax_object TEXT, p_tax_rate NUMERIC, p_effective_from DATE
) RETURNS public.company_tax_profiles
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE
  prior public.company_tax_profiles;
  result public.company_tax_profiles;
BEGIN
  PERFORM 1 FROM public.companies WHERE id = p_company_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Company not found'; END IF;
  IF p_tax_object NOT IN ('USN_INCOME','USN_INCOME_MINUS_EXPENSES')
    OR p_tax_rate IS NULL OR p_tax_rate <= 0 OR p_tax_rate > 100
    OR p_tax_rate <> round(p_tax_rate, 2) OR p_effective_from IS NULL THEN
    RAISE EXCEPTION 'Invalid tax profile';
  END IF;
  SELECT * INTO prior FROM public.company_tax_profiles
    WHERE company_id = p_company_id ORDER BY effective_from DESC LIMIT 1 FOR UPDATE;
  IF FOUND THEN
    IF p_effective_from <= (now() AT TIME ZONE 'Europe/Moscow')::date
      OR p_effective_from <= prior.effective_from THEN
      RAISE EXCEPTION 'Existing tax elections may only be superseded on a future date';
    END IF;
    IF prior.effective_to IS NULL OR prior.effective_to >= p_effective_from THEN
      UPDATE public.company_tax_profiles SET effective_to = p_effective_from - 1,
        updated_at = now() WHERE id = prior.id;
    END IF;
  END IF;
  INSERT INTO public.company_tax_profiles(company_id, tax_object, tax_rate, effective_from)
  VALUES (p_company_id, p_tax_object, p_tax_rate, p_effective_from)
  RETURNING * INTO result;
  RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION public.orion_append_company_tax_profile(BIGINT,TEXT,NUMERIC,DATE) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.orion_append_company_tax_profile(BIGINT,TEXT,NUMERIC,DATE) TO service_role;

-- Company onboarding either creates both rows or neither. Existing legacy companies stay unconfigured.
CREATE FUNCTION public.orion_create_company_with_tax_profile(
  p_name TEXT, p_country TEXT, p_currency TEXT, p_timezone TEXT, p_language TEXT,
  p_is_default BOOLEAN, p_tax_object TEXT, p_tax_rate NUMERIC, p_effective_from DATE
) RETURNS public.companies
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE result public.companies;
BEGIN
  IF p_name IS NULL OR btrim(p_name) = '' THEN RAISE EXCEPTION 'Company name is required'; END IF;
  IF p_tax_object NOT IN ('USN_INCOME','USN_INCOME_MINUS_EXPENSES')
    OR p_tax_rate IS NULL OR p_tax_rate <= 0 OR p_tax_rate > 100
    OR p_tax_rate <> round(p_tax_rate, 2) OR p_effective_from IS NULL THEN
    RAISE EXCEPTION 'Invalid tax profile';
  END IF;
  IF COALESCE(p_is_default, false) THEN
    UPDATE public.companies SET is_default = false WHERE is_default = true;
  END IF;
  INSERT INTO public.companies(name, country, currency, timezone, language, is_default, status, default_tax_percent)
  VALUES (btrim(p_name), NULLIF(btrim(p_country),''), COALESCE(NULLIF(btrim(p_currency),''),'RUB'),
    COALESCE(NULLIF(btrim(p_timezone),''),'Europe/Moscow'), COALESCE(NULLIF(btrim(p_language),''),'ru'),
    COALESCE(p_is_default,false), 'active', 6)
  RETURNING * INTO result;
  INSERT INTO public.company_tax_profiles(company_id, tax_object, tax_rate, effective_from)
  VALUES (result.id, p_tax_object, p_tax_rate, p_effective_from);
  RETURN result;
END;
$$;
REVOKE ALL ON FUNCTION public.orion_create_company_with_tax_profile(TEXT,TEXT,TEXT,TEXT,TEXT,BOOLEAN,TEXT,NUMERIC,DATE)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.orion_create_company_with_tax_profile(TEXT,TEXT,TEXT,TEXT,TEXT,BOOLEAN,TEXT,NUMERIC,DATE)
  TO service_role;

CREATE TABLE public.company_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  expense_date DATE NOT NULL,
  category TEXT NOT NULL CHECK (category IN (
    'ACCOUNTING','RENT','SOFTWARE','ADVERTISING','LOGISTICS','BANKING','PAYROLL',
    'OFFICE','PROFESSIONAL_SERVICES','TAXES_FEES','FINES_PENALTIES','PERSONAL_GROCERIES','OTHER'
  )),
  description TEXT NOT NULL CHECK (length(btrim(description)) BETWEEN 1 AND 500),
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  tax_deductible BOOLEAN NOT NULL DEFAULT false,
  category_default BOOLEAN NOT NULL DEFAULT false,
  tax_deductible_origin TEXT NOT NULL CHECK (tax_deductible_origin IN ('CATEGORY_DEFAULT','USER_OVERRIDE')),
  evidence_status TEXT NOT NULL DEFAULT 'UNVERIFIED' CHECK (evidence_status IN ('UNVERIFIED','VERIFIED','REJECTED')),
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);
CREATE INDEX company_expenses_company_date ON public.company_expenses(company_id, expense_date DESC) WHERE deleted_at IS NULL;

CREATE TABLE public.company_expense_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  expense_id BIGINT NOT NULL REFERENCES public.company_expenses(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('CREATE','UPDATE','DELETE')),
  old_row JSONB,
  new_row JSONB,
  changed_by TEXT,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX company_expense_audit_company_expense ON public.company_expense_audit(company_id, expense_id, changed_at);

CREATE FUNCTION public.orion_audit_company_expense() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Hard delete of company expenses is forbidden';
  END IF;
  IF TG_OP = 'UPDATE' AND OLD.company_id <> NEW.company_id THEN
    RAISE EXCEPTION 'Company expense ownership cannot change';
  END IF;
  INSERT INTO public.company_expense_audit(company_id, expense_id, action, old_row, new_row, changed_by)
  VALUES (NEW.company_id, NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN 'CREATE' WHEN OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN 'DELETE' ELSE 'UPDATE' END,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE to_jsonb(OLD) END,
    to_jsonb(NEW), NEW.updated_by);
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.orion_audit_company_expense() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER company_expense_audit_write AFTER INSERT OR UPDATE OR DELETE ON public.company_expenses
  FOR EACH ROW EXECUTE FUNCTION public.orion_audit_company_expense();

-- Direct browser access is read-only and tenant-scoped. Authorized route handlers write with service_role.
ALTER TABLE public.company_tax_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_expense_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.company_tax_profiles, public.company_expenses, public.company_expense_audit FROM anon, authenticated;
GRANT SELECT ON public.company_tax_profiles, public.company_expenses, public.company_expense_audit TO authenticated;
GRANT ALL ON public.company_tax_profiles, public.company_expenses, public.company_expense_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.company_tax_profiles_id_seq, public.company_expenses_id_seq,
  public.company_expense_audit_id_seq TO service_role;
CREATE POLICY tenant_read_tax_profiles ON public.company_tax_profiles FOR SELECT TO authenticated
  USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY tenant_read_company_expenses ON public.company_expenses FOR SELECT TO authenticated
  USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY tenant_read_company_expense_audit ON public.company_expense_audit FOR SELECT TO authenticated
  USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY service_all_tax_profiles ON public.company_tax_profiles FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_all_company_expenses ON public.company_expenses FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_all_company_expense_audit ON public.company_expense_audit FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE public.company_tax_profiles IS 'Company tax election; existing companies intentionally have no inferred profile.';
COMMENT ON TABLE public.company_expenses IS 'Manual business expense claims; checkbox alone does not prove tax deductibility.';
COMMIT;
