-- Tax Engine V1 Sprint 3B: evidence-based paid-and-sold purchase recognition.
-- Additive only. Existing purchase rows remain unpaid and therefore non-deductible.
BEGIN;

ALTER TABLE public.purchases
  ADD COLUMN payment_status TEXT NOT NULL DEFAULT 'UNPAID',
  ADD COLUMN payment_date DATE,
  ADD COLUMN paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN payment_reference TEXT,
  ADD COLUMN payment_fx_rate NUMERIC(14,6),
  ADD COLUMN payment_fx_reference TEXT;

ALTER TABLE public.purchases
  ADD CONSTRAINT purchases_payment_status_check
    CHECK (payment_status IN ('UNPAID','PARTIALLY_PAID','PAID')),
  ADD CONSTRAINT purchases_paid_amount_check CHECK (paid_amount >= 0),
  ADD CONSTRAINT purchases_payment_fx_rate_check
    CHECK (payment_fx_rate IS NULL OR payment_fx_rate > 0),
  ADD CONSTRAINT purchases_payment_evidence_check CHECK (
    (payment_status = 'UNPAID' AND paid_amount = 0 AND payment_date IS NULL)
    OR (payment_status IN ('PARTIALLY_PAID','PAID') AND paid_amount > 0 AND payment_date IS NOT NULL)
  );

CREATE TABLE public.company_purchase_tax_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE,
  allocation_method TEXT NOT NULL CHECK (allocation_method = 'FIFO'),
  payment_policy TEXT NOT NULL CHECK (payment_policy = 'FULL_PAYMENT_ONLY'),
  return_policy TEXT NOT NULL CHECK (return_policy = 'RETURN_EVENT_DATE'),
  effective_from DATE NOT NULL,
  evidence_reference TEXT NOT NULL CHECK (length(btrim(evidence_reference)) BETWEEN 1 AND 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.purchase_payment_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  purchase_id BIGINT NOT NULL REFERENCES public.purchases(id) ON DELETE CASCADE,
  old_payment JSONB,
  new_payment JSONB NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX purchase_payment_audit_company_purchase
  ON public.purchase_payment_audit(company_id, purchase_id, changed_at DESC);

CREATE FUNCTION public.orion_audit_purchase_payment() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
DECLARE owner_company_id BIGINT;
BEGIN
  IF TG_OP = 'UPDATE' AND NOT (
    OLD.payment_status IS DISTINCT FROM NEW.payment_status OR
    OLD.payment_date IS DISTINCT FROM NEW.payment_date OR
    OLD.paid_amount IS DISTINCT FROM NEW.paid_amount OR
    OLD.payment_reference IS DISTINCT FROM NEW.payment_reference OR
    OLD.payment_fx_rate IS DISTINCT FROM NEW.payment_fx_rate OR
    OLD.payment_fx_reference IS DISTINCT FROM NEW.payment_fx_reference
  ) THEN
    RETURN NEW;
  END IF;

  SELECT company_id INTO STRICT owner_company_id
  FROM public.marketplace_accounts WHERE id = NEW.marketplace_account_id;

  INSERT INTO public.purchase_payment_audit(company_id, purchase_id, old_payment, new_payment)
  VALUES (
    owner_company_id,
    NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE jsonb_build_object(
      'payment_status', OLD.payment_status, 'payment_date', OLD.payment_date,
      'paid_amount', OLD.paid_amount, 'payment_reference', OLD.payment_reference,
      'payment_fx_rate', OLD.payment_fx_rate, 'payment_fx_reference', OLD.payment_fx_reference
    ) END,
    jsonb_build_object(
      'payment_status', NEW.payment_status, 'payment_date', NEW.payment_date,
      'paid_amount', NEW.paid_amount, 'payment_reference', NEW.payment_reference,
      'payment_fx_rate', NEW.payment_fx_rate, 'payment_fx_reference', NEW.payment_fx_reference
    )
  );
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.orion_audit_purchase_payment() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER purchase_payment_audit_write
  AFTER INSERT OR UPDATE OF payment_status, payment_date, paid_amount,
    payment_reference, payment_fx_rate, payment_fx_reference ON public.purchases
  FOR EACH ROW EXECUTE FUNCTION public.orion_audit_purchase_payment();

CREATE TABLE public.tax_purchase_recognition_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE CHECK (length(event_key) BETWEEN 1 AND 500),
  company_id BIGINT NOT NULL REFERENCES public.companies(id) ON DELETE RESTRICT,
  marketplace_account_id BIGINT NOT NULL REFERENCES public.marketplace_accounts(id) ON DELETE RESTRICT,
  purchase_id BIGINT NOT NULL REFERENCES public.purchases(id) ON DELETE RESTRICT,
  purchase_line_id BIGINT NOT NULL REFERENCES public.purchase_lines(id) ON DELETE RESTRICT,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  source_sale_row_id BIGINT NOT NULL REFERENCES public.wb_sales(id) ON DELETE RESTRICT,
  source_sale_id TEXT NOT NULL,
  source_srid TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('RECOGNITION','REVERSAL')),
  recognition_date DATE NOT NULL,
  quantity NUMERIC(14,4) NOT NULL CHECK (quantity > 0),
  unit_cost_rub NUMERIC(14,4) NOT NULL CHECK (unit_cost_rub >= 0),
  amount_rub NUMERIC(14,2) NOT NULL,
  reversal_of_event_key TEXT REFERENCES public.tax_purchase_recognition_events(event_key) ON DELETE RESTRICT,
  allocation_method TEXT NOT NULL CHECK (allocation_method = 'FIFO'),
  rule_version TEXT NOT NULL DEFAULT 'TAX_PURCHASE_FIFO_V1',
  evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT tax_purchase_recognition_sign_check CHECK (
    (event_type = 'RECOGNITION' AND amount_rub >= 0 AND reversal_of_event_key IS NULL)
    OR (event_type = 'REVERSAL' AND amount_rub <= 0 AND reversal_of_event_key IS NOT NULL)
  ),
  CONSTRAINT tax_purchase_recognition_source_unique
    UNIQUE (company_id, source_sale_row_id, purchase_line_id, event_type)
);
CREATE INDEX tax_purchase_recognition_company_date
  ON public.tax_purchase_recognition_events(company_id, recognition_date, id);
CREATE INDEX tax_purchase_recognition_line
  ON public.tax_purchase_recognition_events(company_id, purchase_line_id, event_type);
CREATE INDEX tax_purchase_recognition_source
  ON public.tax_purchase_recognition_events(company_id, source_srid, event_type);

CREATE FUNCTION public.orion_validate_tax_purchase_recognition() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
DECLARE
  purchase_account_id BIGINT;
  purchase_line_purchase_id BIGINT;
  purchase_line_product_id BIGINT;
  sale_account_id BIGINT;
  sale_product_id BIGINT;
  owner_company_id BIGINT;
BEGIN
  SELECT marketplace_account_id INTO STRICT purchase_account_id
  FROM public.purchases WHERE id = NEW.purchase_id;
  SELECT purchase_id, product_id INTO STRICT purchase_line_purchase_id, purchase_line_product_id
  FROM public.purchase_lines WHERE id = NEW.purchase_line_id;
  SELECT marketplace_account_id, product_id INTO STRICT sale_account_id, sale_product_id
  FROM public.wb_sales WHERE id = NEW.source_sale_row_id;
  SELECT company_id INTO STRICT owner_company_id
  FROM public.marketplace_accounts WHERE id = purchase_account_id;

  IF purchase_line_purchase_id <> NEW.purchase_id OR purchase_line_product_id <> NEW.product_id
    OR sale_product_id <> NEW.product_id OR sale_account_id <> NEW.marketplace_account_id
    OR owner_company_id <> NEW.company_id
    OR NOT EXISTS (
      SELECT 1 FROM public.marketplace_accounts
      WHERE id = sale_account_id AND company_id = NEW.company_id
    ) THEN
    RAISE EXCEPTION 'Tax purchase recognition ownership/evidence mismatch';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.orion_validate_tax_purchase_recognition() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER tax_purchase_recognition_validate
  BEFORE INSERT ON public.tax_purchase_recognition_events
  FOR EACH ROW EXECUTE FUNCTION public.orion_validate_tax_purchase_recognition();

CREATE FUNCTION public.orion_tax_purchase_recognition_append_only() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  RAISE EXCEPTION 'Tax purchase recognition events are append-only';
END;
$$;
REVOKE ALL ON FUNCTION public.orion_tax_purchase_recognition_append_only() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER tax_purchase_recognition_append_only
  BEFORE UPDATE OR DELETE ON public.tax_purchase_recognition_events
  FOR EACH ROW EXECUTE FUNCTION public.orion_tax_purchase_recognition_append_only();

ALTER TABLE public.company_purchase_tax_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_payment_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tax_purchase_recognition_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.company_purchase_tax_policies, public.purchase_payment_audit,
  public.tax_purchase_recognition_events FROM anon, authenticated;
GRANT SELECT ON public.company_purchase_tax_policies, public.purchase_payment_audit,
  public.tax_purchase_recognition_events TO authenticated;
GRANT SELECT, INSERT ON public.company_purchase_tax_policies TO service_role;
GRANT SELECT, INSERT ON public.purchase_payment_audit TO service_role;
GRANT SELECT, INSERT ON public.tax_purchase_recognition_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.company_purchase_tax_policies_id_seq,
  public.purchase_payment_audit_id_seq, public.tax_purchase_recognition_events_id_seq TO service_role;

CREATE POLICY tenant_read_purchase_tax_policies ON public.company_purchase_tax_policies
  FOR SELECT TO authenticated USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY tenant_read_purchase_payment_audit ON public.purchase_payment_audit
  FOR SELECT TO authenticated USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY tenant_read_tax_purchase_recognition ON public.tax_purchase_recognition_events
  FOR SELECT TO authenticated USING (company_id = ANY (public.orion_jwt_company_ids()));
CREATE POLICY service_all_purchase_tax_policies ON public.company_purchase_tax_policies
  FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY service_insert_purchase_payment_audit ON public.purchase_payment_audit
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY service_select_purchase_payment_audit ON public.purchase_payment_audit
  FOR SELECT TO service_role USING (true);
CREATE POLICY service_insert_tax_purchase_recognition ON public.tax_purchase_recognition_events
  FOR INSERT TO service_role WITH CHECK (true);
CREATE POLICY service_select_tax_purchase_recognition ON public.tax_purchase_recognition_events
  FOR SELECT TO service_role USING (true);

COMMENT ON TABLE public.company_purchase_tax_policies IS
  'Explicit per-company tax purchase policy. No row is inferred or seeded for existing companies.';
COMMENT ON COLUMN public.purchases.payment_status IS
  'Tax evidence state. Purchase creation defaults to UNPAID and never implies payment.';
COMMENT ON TABLE public.tax_purchase_recognition_events IS
  'Append-only FIFO paid-and-sold tax cost recognition and return reversals; separate from Product Cost and Financial Engine V4.';

COMMIT;
